<?php
/** @var \M2E\Multichannel\Block\Adminhtml\Dashboard\Tabs\TabContent $block */

?>
<?php
$extension = $block->getExtension();
$metadata = $extension->getMetadata();
?>

<div class="m2e-multichannel-tab">
    <?php
    if ($extension->isEnabled()) { ?>
        <h2><?= /* @noEscape */ $extension->getTitle() ?><span class="installed"><?= /* @noEscape */ __('Installed') ?></span></h2>
        <div class="section-title"><?= /* @noEscape */ __('Resources & Support') ?></div>
        <div class="resources">
            <p><a href="<?= /* @noEscape */ $metadata->getDocsUrl() ?>" target="_blank"><?= /* @noEscape */ __('User Documentation') ?></a></p>
            <p><a href="<?= /* @noEscape */ $metadata->getSupportUrl() ?>" target="_blank"><?= /* @noEscape */ __('Contact Support') ?></a></p>
        </div>
        <a href="<?= /* @noEscape */ $metadata->getMarketplaceUrl() ?>" target="_blank">
            <?= /* @noEscape */ __('Upgrade') ?> <?= /* @noEscape */ $extension->getTitle() ?>
        </a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= /* @noEscape */ $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } else { ?>
        <h2><?= /* @noEscape */ $extension->getTitle() ?><span class="not-installed"><?= /* @noEscape */ __('Not Installed') ?></span></h2>
        <p class="description"><?= /* @noEscape */ __(
                'Connect your Adobe Commerce (Magento) store with global eBay marketplaces, including '
                . 'eBay Motors. Automate listings, inventory sync, and order management for a smooth multichannel'
                . ' selling experience.'
            ) ?></p>

        <div class="section-title"><?= /* @noEscape */ __('Key Features') ?>:</div>
        <ul>
            <li><b><?= /* @noEscape */ __('Automated listings') ?></b> – <?= /* @noEscape */ __(
                    'List and update products on eBay from your Magento system.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('Real-time inventory sync') ?></b> – <?= /* @noEscape */ __(
                    'Prevent overselling with automatic stock updates.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('Centralized order management') ?></b> – <?= /* @noEscape */ __('Handle eBay orders directly in Magento.') ?>
            </li>
            <li><b><?= /* @noEscape */ __('Flexible stock & pricing rules') ?></b> – <?= /* @noEscape */ __(
                    'Adjust quantities and prices dynamically per marketplace.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('eBay Motors compatibility') ?></b> – <?= /* @noEscape */ __(
                    'List auto parts with the Parts Compatibility feature.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('Promotional tools') ?></b> – <?= /* @noEscape */ __('Apply and manage eBay promotions for your listings.') ?>
            </li>
        </ul>

        <p><a href="<?= /* @noEscape */ $metadata->getMarketplaceUrl() ?>" target="_blank">
                <?= /* @noEscape */ __('Install') ?> <?= /* @noEscape */ $extension->getTitle() ?>
            </a></p>
        <p><a href="<?= /* @noEscape */ $metadata->getDocInstallUrl() ?>" target="_blank"><?= /* @noEscape */ __(
                    'View Installation Steps'
                ) ?></a></p>
        <a href="<?= /* @noEscape */ $metadata->getSupportUrl() ?>" target="_blank"><?= /* @noEscape */ __('Contact Support') ?></a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= /* @noEscape */ $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } ?>
</div>
