<?php
/** @var \M2E\Multichannel\Block\Adminhtml\Dashboard\Tabs\TabContent $block */

?>
<?php
$extension = $block->getExtension();
$metadata = $extension->getMetadata();
?>

<div class="m2e-multichannel-tab">
    <?php
    if ($extension->isEnabled()) { ?>
        <h2><?= /* @noEscape */ $extension->getTitle() ?><span class="installed"><?= /* @noEscape */ __('Installed') ?></span></h2>
        <div class="section-title"><?= /* @noEscape */ __('Resources & Support') ?></div>
        <div class="resources">
            <p><a href="<?= /* @noEscape */ $metadata->getDocsUrl() ?>" target="_blank"><?= /* @noEscape */ __('User Documentation') ?></a></p>
            <p><a href="<?= /* @noEscape */ $metadata->getSupportUrl() ?>" target="_blank"><?= /* @noEscape */ __('Contact Support') ?></a></p>
        </div>
        <a href="<?= /* @noEscape */ $metadata->getMarketplaceUrl() ?>" target="_blank">
            <?= /* @noEscape */ __('Upgrade') ?> <?= /* @noEscape */ $extension->getTitle() ?>
        </a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= /* @noEscape */ $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } else { ?>
        <h2><?= /* @noEscape */ $extension->getTitle() ?><span class="not-installed"><?= /* @noEscape */ __('Not Installed') ?></span></h2>
        <p><a href="<?= /* @noEscape */ $metadata->getMarketplaceUrl() ?>" target="_blank">
                <?= /* @noEscape */ __('Install') ?> <?= /* @noEscape */ $extension->getTitle() ?>
            </a></p>
        <p><a href="<?= /* @noEscape */ $metadata->getDocInstallUrl() ?>" target="_blank"><?= /* @noEscape */ __(
                    'View Installation Steps'
                ) ?></a></p>
        <a href="<?= /* @noEscape */ $metadata->getSupportUrl() ?>" target="_blank"><?= /* @noEscape */ __('Contact Support') ?></a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= /* @noEscape */ $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } ?>
</div>
