<?php
/** @var \M2E\Multichannel\Block\Adminhtml\Dashboard\Tabs\TabContent $block */

?>
<?php
$extension = $block->getExtension();
$metadata = $extension->getMetadata();
?>

<div class="m2e-multichannel-tab">
    <?php
    if ($extension->isEnabled()) { ?>
        <h2><?= $extension->getTitle() ?><span class="installed"><?= __('Installed') ?></span></h2>
        <div class="section-title"><?= __('Resources & Support') ?></div>
        <div class="resources">
            <p><a href="<?= $metadata->getDocsUrl() ?>" target="_blank"><?= __('User Documentation') ?></a></p>
            <p><a href="<?= $metadata->getSupportUrl() ?>" target="_blank"><?= __('Contact Support') ?></a></p>
        </div>
        <a href="<?= $metadata->getMarketplaceUrl() ?>" target="_blank">
            <?= __('Upgrade') ?> <?= $extension->getTitle() ?>
        </a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } else { ?>
        <h2><?= $extension->getTitle() ?><span class="not-installed"><?= __('Not Installed') ?></span></h2>
        <p class="description"><?= __(
                'Connect your Adobe Commerce (Magento) store with TikTok Shop and reach a vast audience in '
                . 'multiple countries across the globe.'
            ) ?></p>

        <div class="section-title"><?= __('Key Features') ?>:</div>
        <ul>
            <li><b><?= __('Easy product listing') ?></b> – <?= __(
                    'Quickly list and categorize products from Magento on TikTok Shop.'
                ) ?></li>
            <li><b><?= __('Real-time inventory synchronization') ?></b> – <?= __(
                    'Automatically update stock levels to prevent overselling.'
                ) ?></li>
            <li><b><?= __('Centralized order management') ?></b> – <?= __(
                    'Handle TikTok Shop orders directly within Magento.'
                ) ?></li>
            <li><b><?= __('Flexible stock & pricing rules') ?></b> – <?= __(
                    'Adjust product quantities and prices dynamically for TikTok Shop.'
                ) ?></li>
            <li><b><?= __('Promotional tools') ?></b> – <?= __(
                    'Manage items with TikTok Shop promotions applied.'
                ) ?></li>
        </ul>

        <p><a href="<?= $metadata->getMarketplaceUrl() ?>" target="_blank">
                <?= __('Install') ?> <?= $extension->getTitle() ?>
            </a></p>
        <p><a href="<?= $metadata->getDocInstallUrl() ?>" target="_blank"><?= __(
                    'View Installation Steps'
                ) ?></a></p>
        <a href="<?= $metadata->getSupportUrl() ?>" target="_blank"><?= __('Contact Support') ?></a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } ?>
</div>
