<?php
/** @var \M2E\Multichannel\Block\Adminhtml\Dashboard\Tabs\TabContent $block */

?>
<?php
$extension = $block->getExtension();
$metadata = $extension->getMetadata();
?>

<div class="m2e-multichannel-tab">
    <?php
    if ($extension->isEnabled()) { ?>
        <h2><?= $extension->getTitle() ?><span class="installed"><?= __('Installed') ?></span></h2>
        <div class="section-title"><?= __('Resources & Support') ?></div>
        <div class="resources">
            <p><a href="<?= $metadata->getDocsUrl() ?>" target="_blank"><?= __('User Documentation') ?></a></p>
            <p><a href="<?= $metadata->getSupportUrl() ?>" target="_blank"><?= __('Contact Support') ?></a></p>
        </div>
        <a href="<?= $metadata->getMarketplaceUrl() ?>" target="_blank">
            <?= __('Upgrade') ?> <?= $extension->getTitle() ?>
        </a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } else { ?>
        <h2><?= $extension->getTitle() ?><span class="not-installed"><?= __('Not Installed') ?></span></h2>
        <p class="description"><?= __(
                'Connect your Adobe Commerce (Magento) store with Walmart U.S. and Canadian marketplaces, '
                . 'reaching over 120 million online shoppers monthly.'
            ) ?></p>

        <div class="section-title"><?= __('Key Features') ?>:</div>
        <ul>
            <li><b><?= __('Automated product mapping') ?></b> – <?= __(
                    'Link your Magento products to Walmart\'s catalog.'
                ) ?></li>
            <li><b><?= __('Centralized order management') ?></b> – <?= __(
                    'Handle Walmart orders directly within Magento.'
                ) ?></li>
            <li><b><?= __('Walmart Fulfillment Services (WFS) support') ?></b> – <?= __(
                    'Integrate and manage WFS orders.'
                ) ?></li>
            <li><b><?= __('Unique SKU generation') ?></b> – <?= __('Prevent duplicate SKUs and data inaccuracies.') ?>
            </li>
            <li><b><?= __('Promotional tools') ?></b> – <?= __(
                    'Use \'Clearance\' and \'Reduced Price\' badges to boost sales.'
                ) ?></li>
            <li><b><?= __('Custom shipping options') ?></b> – <?= __(
                    'Offer various shipping carriers and create smart shipping rules.'
                ) ?></li>
        </ul>

        <p><a href="<?= $metadata->getMarketplaceUrl() ?>" target="_blank">
                <?= __('Install') ?> <?= $extension->getTitle() ?>
            </a></p>
        <p><a href="<?= $metadata->getDocInstallUrl() ?>" target="_blank"><?= __(
                    'View Installation Steps'
                ) ?></a></p>
        <a href="<?= $metadata->getSupportUrl() ?>" target="_blank"><?= __('Contact Support') ?></a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } ?>
</div>
