<?php
/** @var \M2E\Multichannel\Block\Adminhtml\Dashboard\Tabs\TabContent $block */

?>
<?php
$extension = $block->getExtension();
$metadata = $extension->getMetadata();
?>

<div class="m2e-multichannel-tab">
    <?php
    if ($extension->isEnabled()) { ?>
        <h2><?= /* @noEscape */ $extension->getTitle() ?><span class="installed"><?= /* @noEscape */ __('Installed') ?></span></h2>
        <div class="section-title"><?= /* @noEscape */ __('Resources & Support') ?></div>
        <div class="resources">
            <p><a href="<?= /* @noEscape */ $metadata->getDocsUrl() ?>" target="_blank"><?= /* @noEscape */ __('User Documentation') ?></a></p>
            <p><a href="<?= /* @noEscape */ $metadata->getSupportUrl() ?>" target="_blank"><?= /* @noEscape */ __('Contact Support') ?></a></p>
        </div>
        <a href="<?= /* @noEscape */ $metadata->getMarketplaceUrl() ?>" target="_blank">
            <?= /* @noEscape */ __('Upgrade') ?> <?= /* @noEscape */ $extension->getTitle() ?>
        </a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= /* @noEscape */ $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } else { ?>
        <h2><?= /* @noEscape */ $extension->getTitle() ?><span class="not-installed"><?= /* @noEscape */ __('Not Installed') ?></span></h2>
        <p class="description"><?= /* @noEscape */ __(
                'Connect your Adobe Commerce (Magento) store with Walmart U.S. and Canadian marketplaces, '
                . 'reaching over 120 million online shoppers monthly.'
            ) ?></p>

        <div class="section-title"><?= /* @noEscape */ __('Key Features') ?>:</div>
        <ul>
            <li><b><?= /* @noEscape */ __('Automated product mapping') ?></b> – <?= /* @noEscape */ __(
                    'Link your Magento products to Walmart\'s catalog.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('Centralized order management') ?></b> – <?= /* @noEscape */ __(
                    'Handle Walmart orders directly within Magento.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('Walmart Fulfillment Services (WFS) support') ?></b> – <?= /* @noEscape */ __(
                    'Integrate and manage WFS orders.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('Unique SKU generation') ?></b> – <?= /* @noEscape */ __('Prevent duplicate SKUs and data inaccuracies.') ?>
            </li>
            <li><b><?= /* @noEscape */ __('Promotional tools') ?></b> – <?= /* @noEscape */ __(
                    'Use \'Clearance\' and \'Reduced Price\' badges to boost sales.'
                ) ?></li>
            <li><b><?= /* @noEscape */ __('Custom shipping options') ?></b> – <?= /* @noEscape */ __(
                    'Offer various shipping carriers and create smart shipping rules.'
                ) ?></li>
        </ul>

        <p><a href="<?= /* @noEscape */ $metadata->getMarketplaceUrl() ?>" target="_blank">
                <?= /* @noEscape */ __('Install') ?> <?= /* @noEscape */ $extension->getTitle() ?>
            </a></p>
        <p><a href="<?= /* @noEscape */ $metadata->getDocInstallUrl() ?>" target="_blank"><?= /* @noEscape */ __(
                    'View Installation Steps'
                ) ?></a></p>
        <a href="<?= /* @noEscape */ $metadata->getSupportUrl() ?>" target="_blank"><?= /* @noEscape */ __('Contact Support') ?></a>
        <?php
        if ($extension->getDescription()) { ?>
            <div><?= /* @noEscape */ $extension->getDescription() ?></div>
            <?php
        } ?>
        <?php
    } ?>
</div>
