<?php
/** @var \M2E\Multichannel\Block\Adminhtml\Menu $block */

?>
<?php
if ($block->isUnifyModeEnabled()) { ?>
    <style>
        <?= /* @noEscape */ $block->getMenuIdsForHide(); ?>
        {
            display: none;
        }
    </style>

    <script type="text/x-magento-init">
        {
            "*": {
                "M2E_Multichannel/js/menu": {
                    "menuConfigs": <?= /* @noEscape */ $block->getJsonConfig(); ?>
        }
    }
}
    </script>
    <?php
} ?>
